name: nextjs-ci

# PR作成のタイミングで起動
on:
  pull_request:

# このワークフローで実行されるジョブを定義
jobs:
  # ジョブの名前を定義
  nextjs-ci:
    # このジョブを実行する環境（GitHub Actionsランナー）を指定
    # 今回はubuntuを指定
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 使用するNode.jsのバージョンを定義
        node-version: [20.12.2]

    # 自動化したい作業を定義
    steps:
      # リポジトリからソースコードの取得
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Node.jsのセットアップ
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        # ESLintで静的解析の実行
        run: npm run lint
      - name: Test code
        # Jestによるテストの実行
        run: npm run test
